auth:
  jwt:
    expires: '90000s'
    secret: ${JWT_SECRET}
  url: http://auth.devseeder.com
  clientToken: ${AUTH_TOKEN}
database:
  mongodb:
    connection: 'mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_URL_CONNECTION}${MONGODB_DATABASE_NAME}${MONGODB_SUFIX_PARAMS}'
api:
  port: ${API_PORT}
doc:
  version: 0.0.1
  name: 'Otaku Manager'
  projectKey: 'OTK_MNG'
